services:
  fraud-api-1: &fraud-api
    container_name: fraud-api-1
    build:
      context: ./fraud-api
      dockerfile: Dockerfile
    volumes:
      - ./fraud-api/vector-index:/app/vector-index:rw
      - ./fraud-api/tests:/app/tests:ro
      - rinha-sockets:/tmp/rinha
      - zig-cache:/tmp/zig-cache
      - ./fraud-api/main_debug:/app/main:ro
    networks:
      - rinha-net
    restart: on-failure
    environment:
      - INSTANCE_ID=1
      - ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache
      - ZIG_CACHE_DIR=/tmp/zig-cache
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '350MB'

  fraud-api-2:
    <<: *fraud-api
    container_name: fraud-api-2
    environment:
      - INSTANCE_ID=2

  load-balancer:
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    container_name: load-balancer
    ports:
      - '9999:9999'
    volumes:
      - ./load-balancer/tests:/app/tests:ro
      - rinha-sockets:/tmp/rinha
      - zig-cache:/tmp/zig-cache
      - ./load-balancer/main_lb:/app/main:ro
    environment:
      - ZIG_GLOBAL_CACHE_DIR=/tmp/zig-cache
      - ZIG_CACHE_DIR=/tmp/zig-cache
    networks:
      - rinha-net
    restart: always
    depends_on:
      - fraud-api-1
      - fraud-api-2
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '300MB'

networks:
  rinha-net:
    driver: bridge

volumes:
  rinha-sockets:
  zig-cache:
