services:
  fraud-api-1:
    build:
      context: ./fraud-api
      dockerfile: Dockerfile
    container_name: fraud-api-1
    environment:
      - INSTANCE_ID=1
      - UDS_PATH=/tmp/rinha/api-1.sock
      - DATA_DIR=/app/data
    volumes:
      - ./fraud-api/src:/app/src
      - rinha-sockets:/tmp/rinha
    networks:
      - rinha-net
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128MB'

  fraud-api-2:
    build:
      context: ./fraud-api
      dockerfile: Dockerfile
    container_name: fraud-api-2
    environment:
      - INSTANCE_ID=2
      - UDS_PATH=/tmp/rinha/api-2.sock
      - DATA_DIR=/app/data
    volumes:
      - ./fraud-api/src:/app/src
      - rinha-sockets:/tmp/rinha
    networks:
      - rinha-net
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128MB'

  load-balancer:
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    container_name: load-balancer
    ports:
      - "9999:9999"
    volumes:
      - ./load-balancer/src:/app/src
      - rinha-sockets:/tmp/rinha
    networks:
      - rinha-net
    restart: on-failure
    depends_on:
      - fraud-api-1
      - fraud-api-2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '94MB'
    command: ["/app/main"]

  preprocess:
    build:
      context: ./preprocess
      dockerfile: Dockerfile
    container_name: preprocess
    volumes:
      - ./preprocess/src:/app/src
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'

networks:
  rinha-net:
    driver: bridge

volumes:
  rinha-sockets:
