services:
  server-1: &server
    container_name: server-1
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./fraud-engine/vector-index:/app/fraud-engine/vector-index:rw
      - rinha-sockets:/tmp/rinha
    networks:
      - rinha-net
    restart: on-failure
    environment:
      - INSTANCE_ID=1
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: '160MB'

  server-2:
    <<: *server
    container_name: server-2
    environment:
      - INSTANCE_ID=2

  haproxy:
    image: haproxy:lts-alpine
    container_name: haproxy
    user: '0:0'
    ports:
      - '9999:9999'
    depends_on:
      - server-1
      - server-2
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - rinha-sockets:/tmp/rinha
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '30MB'

networks:
  rinha-net:
    driver: bridge

volumes:
  rinha-sockets:
