services:
  api-1: &api
    container_name: api-1
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./fraud-engine/vector-index:/app/fraud-engine/vector-index:rw
      - rinha-sockets:/tmp/rinha
    networks:
      - rinha-net
    restart: on-failure
    environment:
      - INSTANCE_ID=1
      - MOCK_MODE=${MOCK_MODE:-}
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '143MB'

  api-2:
    <<: *api
    container_name: api-2
    environment:
      - INSTANCE_ID=2
      - MOCK_MODE=${MOCK_MODE:-}

  lb-zig:
    build:
      context: .
      dockerfile: lb-zig/Dockerfile
    container_name: lb-zig
    ports:
      - '9999:9999'
    depends_on:
      - api-1
      - api-2
    volumes:
      - rinha-sockets:/tmp/rinha
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '64MB'

networks:
  rinha-net:
    driver: bridge

volumes:
  rinha-sockets:
