worker_processes 1;
error_log /dev/stderr;
events {
    worker_connections 1024;
}
stream {
    upstream backends {
        server fraud-api-1:8080;
        server fraud-api-2:8080;
    }
    server {
        listen 9999;
        proxy_pass backends;
        proxy_connect_timeout 1s;
        proxy_timeout 3s;
    }
}